name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Check & Build"
      uses: vgaidarji/android-github-actions/build@v1.0.0
      with:
        entrypoint: ./gradlew
        args: check assembleDebug
